# docker-composeのバージョン
version: '3'

services:
  db:
    image: mysql:5.7
    # 文字コードをutf8に指定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: search_laundry_development
      # 仮想コンテナにアクセスするためのポート番号
    ports:
      - "3306:3306"
      # データを永続化する(ホスト側のdb/mysql/volumesをコンテナ側の/var/lib/mysqlに同期する)
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GOOGLE_MAP_API
    volumes:
      - .:/search_laundry
    ports:
      - "3000:3000"
      # db→webの順番に起動を行う
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  mysql-data:
    driver: local