Laundry.create(name: 'コインランドリー豊橋店', address: '豊橋市1-1',opening_date: '2012-1-13', open_time: '7', close_time: '23', show_washing: true, futon_washing: true, washing_machine: true )
Laundry.create(name: 'コインランドリー豊橋東店', address: '豊橋市東1-2',opening_date: '2014-3-13', open_time: '6', close_time: '23', washing_machine: true )
Laundry.create(name: 'コインランドリー豊橋みゆき店', address: '豊橋市南5-2',opening_date: '2014-4-28', open_time: '5', close_time: '23', show_washing: true, washing_machine: true )
Laundry.create(name: 'コインランドリー豊橋朝日店', address: '豊橋市1-5-3',opening_date: '2014-9-7', open_time: '7', close_time: '22', show_washing: true, washing_machine: true )
Laundry.create(name: 'コインランドリー豊川店', address: '豊川市1-48',opening_date: '2015-6-28', open_time: '6', close_time: '23', futon_washing: true, washing_machine: true )
Laundry.create(name: 'コインランドリー豊橋向山店', address: '豊橋市向山町452',opening_date: '2016-12-19', open_time: '7', close_time: '23', washing_machine: true )
Laundry.create(name: 'コインランドリー名古屋西店', address: '名古屋市西区40',opening_date: '2017-1-13', open_time: '6', close_time: '24', show_washing: true, dryer: true )
Laundry.create(name: 'コインランドリー名古屋南通店', address: '名古屋市南区63-9',opening_date: '2018-5-28', open_time: '7', close_time: '23', show_washing: true, dryer: true, washing_machine: true )
Laundry.create(name: 'コインランドリー岡崎店', address: '岡崎市45-83',opening_date: '2019-12-22', open_time: '7', close_time: '23', show_washing: true, dryer: true, washing_machine: true )
Laundry.create(name: 'コインランドリー岡崎東店', address: '岡崎市東町463',opening_date: '2020-6-8', open_time: '6', close_time: '22', futon_washing: true, dryer: false, washing_machine: true )